config/routes.rb
Rails.application.routes.draw do

  resources :patients
  resources :doctors
  resources :histories

  root 'sessions#new'
  get 'signup_patient' => 'patients#new'
  get 'signup_doctor' => 'doctors#new'
  get 'login' => 'sessions#new'
  get 'signin' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_attached_file :avatar
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  has_secure_password
  has_many :histories, inverse_of: :doctor
  has_many :patients, through: :history

  def histories
    History.where(doctor_id: self.id)
  end
end

app/models/history.rb
class History < ActiveRecord::Base
  has_attached_file :attachment
  validates_attachment :attachment,
   content_type: { content_type: [/\Aimage/, "application/pdf"] },
   size: { in: 0..10.kilobytes }
   
  belongs_to :doctors, inverse_of: :histories
  belongs_to :patients

  def doctor
    Doctor.find_by(id: self.doctor_id)
  end

  def patient
    Patient.find_by(id: self.patient_id)
  end

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_secure_password
  has_many :histories, inverse_of: :patient
  has_many :doctors, through: :history

  def histories
    History.where(patient_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_patient
    @current_patient = Patient.find(session[:user_id]) if session[:user_id] 
  end

  def current_doctor
    @current_doctor = Doctor.find(session[:user_id]) if session[:user_id] 
  end

  def require_doctor
    redirect_to '/' unless current_doctor
  end

  def require_patient
    redirect_to '/' unless current_patient
  end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :require_doctor, only: [:index, :show, :edit]
  helper DoctorsHelper

  def index
    @doctors = Doctor.all
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.create(doctor_params)
    if @doctor.save
      session[:user_id] = @doctor.id
      redirect_to "/doctors/#{@doctor.id}"
    else
      redirect_to '/signup'
    end
  end

  def edit
    @doctor = Doctor.find(params[:id])
  end

  def update
    @doctor = current_doctor
    if @doctor.update_attributes(doctor_params)
      redirect_to doctor_path @doctor
    else
      redirect_to action: :edit
    end
  end

  def show
    @doctor = Doctor.find(params[:id])
  end

  private
    def doctor_params
      params.require(:doctor).permit(:name, :surname, :email, :password, :speciality, :speciality_description, :experience_years, :avatar)
    end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :require_doctor, only: [:show, :new, :update]
  def new
    @history = History.new
  end

  def create
    @history = History.create(history_params)
    @history.doctor_id = current_doctor.id
    if @history.save
      redirect_to "/histories/#{@history.id}"
      else
        redirect_to 'histories/new'
      end
  end

  def show
    @history = History.find(params[:id])
  end

  def index
    @histories = History.all
  end

  def update
  end

  private
    def history_params
      params.require(:history).permit(:title, :description)
    end

    def set_history
      @history = History.find(history_params[:id])
    end
      
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :require_patient, only: [:index, :show, :edit]

  def index
    @patients = Patient.all
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.create(patient_params)
    if @patient.save
      session[:user_id] = @patient.id
      redirect_to "/patients/#{@patient.id}"
    else
      redirect_to '/signup'
    end
  end

  def edit
   @patient = Patient.find(params[:id])
  end

  def update
    @patient = current_patient
    if @patient.update_attributes(patient_params)
      redirect_to patient_path(@patient)
    else
      render action: :edit
    end
  end

  def show
    @patient = Patient.find(params[:id])
  end

  private
    def patient_params
      params.require(:patient).permit(:name, :surname, :email, :password)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = Doctor.find_by_email(params[:session][:email]) || Patient.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to "/#{@user.class.to_s.downcase.pluralize}/#{@user.id}"
    else
      redirect_to '/login'
    end 
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_full_name user
    [user.name, user.surname].join(" ") if user
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/doctors/_form.html.erb
<div class='container'>
  <div class='col-md-5'>
    <h1>Sign up as a Doctor</h1>

    <%= form_for @doctor do |f| %>

      <%= f.label :Add_Photo %>:
      <%= f.file_field :avatar, class: 'btn btn-default' %><br />

      <%= f.label :name %>:
      <%= f.text_field :name, class: 'form-control' %><br />

      <%= f.label :surname %>:
      <%= f.text_field :surname, class: 'form-control' %><br />

      <%= f.label :speciality %>:
      <%= f.text_field :speciality, class: 'form-control' %><br />

      <%= f.label :Speciality_Description %>:
      <%= f.text_area :speciality_description, class: 'form-control' %><br />

      <%= f.label :Years_of_experience %>:
      <%= f.select :experience_years, (1..80), class: 'form-control' %><br />
          
      <%= f.label :email %>:
      <%= f.text_field :email, class: 'form-control' %><br />
          
      <%= f.label :password %>:
      <%= f.password_field :password, class: 'form-control' %><br />

      <%= f.submit "Save", class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/doctors/edit.html.erb
<%= render partial: 'form'%>

app/views/doctors/index.html.erb
<div class="container">
  
  <div class="row">
    <% @doctors.in_groups_of(3) do |doctor_line| %>
      <div class="col-md-12 user_line">
        <%doctor_line.compact.each do |doctor|%>
          <div class="col-md-4 user">
            <h3><%=doctor.name + ' ' + doctor.surname%></h3>
            <h5><%=doctor.email%></h5>
          </div>
        <%end%>
      </div>
    <%end%>
  </div>

</div>

app/views/doctors/new.html.erb
<%= render partial: 'form'%>

app/views/doctors/show.html.erb
<div class="container">
  <div class="col-md-4">
    <%=image_tag @doctor.avatar, size: "300x300"%>
    <h3><%=user_full_name @doctor%></h3>
    <h5><%=@doctor.email%></h5>
    <h5><%=@doctor.speciality%></h5>
    <h5><%=@doctor.speciality_description%></h5>
    <h5>Years of Experience: <%=@doctor.experience_years%></h5>


    <div class="histories">
      <%=link_to 'Create history', '/histories/new'%>
    </div>

  </div>

  <div class="col-md-6">
    <%=render partial: 'doctor_history_table'%>
  </div>
</div>

app/views/histories/index.html.erb
<h1>Histories#index</h1>
<div class="container">
  
  <div class="row">
    <% @histories.in_groups_of(3) do |history_line| %>
      <div class="col-md-12 history_line">
        <%history_line.compact.each do |history|%>
          <div class="col-md-4 history">
            <h3><%=history.title%></h3>
            <h5><%=history.description%></h5>
          </div>
        <%end%>
      </div>
    <%end%>
  </div>

</div>

app/views/histories/new.html.erb
<div class='container'>
  <div class='col-md-5'>
    <h1>Create sickness history</h1>

    <%= form_for @history, url: histories_path, html: { multipart: true } do |f| %>

      <%= f.label :title %>:
      <%= f.text_field :title, class: 'form-control' %><br />

      <%= f.label :description %>:
      <%= f.text_area :description, class: 'form-control' %><br />

      <%= f.label :attachment %>:
      <%= f.file_field :attachment, class: 'form-control' %><br />
          
      <%= f.submit "Create", class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/histories/show.html.erb
<div class="container">
  <div class="col-md-4">
    <img src = <%=@history.attachment%>>
    <h3><%=@history.title%></h3>
    <h5><%=@history.description%></h5>
  </div>
</div>

app/views/histories/update.html.erb
<h1>Histories#update</h1>
<p>Find me in app/views/histories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kiddy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "shared/header" %>
  <div class="container content">
    <%= yield %>
  </div>

<%= render "shared/footer" %>
  
</body>

</html>

app/views/patients/_form.html.erb
<div class='container'>
  <div class='col-md-5'>
    <h1>Sign up as a Patient</h1>

    <%= form_for @patient do |f| %>

      <%= f.label :name %>:
      <%= f.text_field :name, class: 'form-control' %><br />

      <%= f.label :surname %>:
      <%= f.text_field :surname, class: 'form-control' %><br />
          
      <%= f.label :email %>:
      <%= f.text_field :email, class: 'form-control' %><br />
          
      <%= f.label :password %>:
      <%= f.password_field :password, class: 'form-control' %><br />

      <%= f.submit "Save", class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/patients/edit.html.erb
<%= render partial: 'form'%>

app/views/patients/index.html.erb
<div class="container">
  
  <div class="row">
    <% @patients.in_groups_of(3) do |patient_line| %>
      <div class="col-md-12 user_line">
        <%patient_line.compact.each do |patient|%>
          <div class="col-md-4 user">
            <h3><%=patient.name + ' ' + patient.surname%></h3>
            <h5><%=patient.email%></h5>
          </div>
        <%end%>
      </div>
    <%end%>
  </div>

</div>

app/views/patients/new.html.erb
<%= render partial: 'form'%>

app/views/patients/show.html.erb
<div class="container">
  <div class="col-md-4">
    <h3><%=user_full_name @patient%></h3>
    <h5><%=@patient.email%></h5>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <p>For more information contact doc@mail.com</p>
  All rights reserved | 2016
</footer>

app/views/shared/_header.html.erb
<div id="top" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <h2>DocPortal</h2>
                </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <%@user = @current_patient || @current_doctor%>
                    <% if @user %>
                      <ul> 
                        <li><%= link_to @user.email, "/#{@user.class.to_s.downcase.pluralize}/#{@user.id}" %></li> 
                        <li><%= link_to "Edit profile", "#{@user.id}" + "/edit" %></li> 
                        <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
                      </ul> 
                    <% else %> 
                      <ul> 
                        <li><%= link_to "Login", 'login' %></a></li> 
                        <li><%= link_to "Signup as a Patient", 'signup_patient' %></a></li>
                        <li><%= link_to "Signup as a Doctor", 'signup_doctor' %></a></li> 
                      </ul> 
                    <% end %>
                </ul>
            </div>
        </div>
  </div>